name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  login:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check secretes
      run: echo ${{ secrets.DOCKERHUB_USERNAME }}
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: edit application property
      run: echo "spring.sendgrid.api.key=${{ secrets.SENDGRID_KEY }}" >> src/main/resources/application.properties
           echo "aws.accessKey=${{ secrets.AWS_KEY }}" >> src/main/resources/application.properties
           echo "aws.secretKey=${{ secrets.AWS_PASSWORD }}" >> src/main/resources/application.properties
    - name: package
      run: |
        pwd
        mvn clean install -DskipTests
        pwd
        ls -al target
    - name: DockerHub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      run: | 
        TAG= ${{ curl --silent "https://api.github.com/repos/Jinshuang-555/advanced_webapp/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")'}}
        docker build -t db:$TAG .
        docker login
        docker tag db:$TAG jinshuangniu/advanced1cloud1computing:app-$TAG
        docker push jinshuangniu/advanced1cloud1computing:app-$TAG
